# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  # - 0.7
  # - 1.0
  # - 1.1
  - 1.2
notifications:
  email: true
env:
  - POPE_NOMASS=true DOCUMENTER_DEBUG=true POPE_NOMATPLOTLIB=true

before_script:
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg;   Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/ggggggggg/QSGRegistry.jl"));  Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/JuliaRegistries/General.git"));  Pkg.status()'

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.status(); Pkg.build(); Pkg.test()'

addons:
  apt:
    packages:
    - hdf5-tools
    - libnlopt0
sudo: required

after_success:
  # deploy docs
  - julia -e 'Pkg.add("Documenter");cd(Pkg.dir("Pope")); include(joinpath("docs", "make.jl"))'
  # push coverage results to Coveralls
  # - julia -e 'cd(Pkg.dir("Pope")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  # - julia -e 'cd(Pkg.dir("Pope")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
