# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  # - 0.7
  - 1.0
  # - 1.1
  # - 1.2
notifications:
  email: true
env:
  - POPE_NOMASS=true DOCUMENTER_DEBUG=true POPE_NOMATPLOTLIB=true

before_script:
  - git clone https://github.com/ggggggggg/ReferenceMicrocalFiles.jl
  - git clone https://github.com/joefowler/ARMA.jl

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - ls -l #Optional command.  Just here to confirm the Dependency is in the folder you think it is.
  - pwd #Optional command. Just here so you can see where you are in the file system to make sure the path is correct below.
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.develop(PackageSpec(path="ReferenceMicrocalFiles.jl")); Pkg.instantiate()'
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.develop(PackageSpec(path="ARMA.jl")); Pkg.instantiate()'
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build();'
  
addons:
  apt:
    packages:
    - hdf5-tools
    - libnlopt0
sudo: required

after_success:
  # deploy docs
  - julia -e 'Pkg.add("Documenter");cd(Pkg.dir("Pope")); include(joinpath("docs", "make.jl"))'
  # push coverage results to Coveralls
  # - julia -e 'cd(Pkg.dir("Pope")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  # - julia -e 'cd(Pkg.dir("Pope")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
