image: julia:0.6.1

pipelines:
  default:
    - step:
        script:
          - julia -e 'Pkg.clone("https://github.com/ggggggggg/ReferenceMicrocalFiles.jl")'
          - ls -a
          - pwd
          - cd ..
          - ls -a
          - cp -r * ~/.julia/v0.6/Pope
          - julia -e 'Pkg.test("Pope")'
