image: julia:0.6.1

pipelines:
  default:
    - step:
        script:
          - julia -e 'Pkg.clone("https://github.com/ggggggggg/ReferenceMicrocalFiles.jl")'
          - julia -e 'Pkg.test("Pope")'
